#!/bin/bash
set -e

echo "🔧 Starting FINAL NUCLEAR Netlify build..."

# Ensure we're in the right directory
cd "$(dirname "$0")"

echo "📦 Installing dependencies (no postinstall)..."
npm ci --ignore-scripts

echo "🗄️ Generating Prisma client..."
npx prisma generate

# Create .nuxt directory
mkdir -p .nuxt

# FORCE create the damn TypeScript config that Vite keeps looking for
echo "📝 FORCE creating tsconfig.app.json to stop Vite from complaining..."
cat > .nuxt/tsconfig.app.json << 'EOF'
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowJs": true,
    "noEmit": true,
    "strict": false,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "jsx": "preserve",
    "paths": {
      "~/*": ["../*"],
      "@/*": ["../*"]
    }
  },
  "include": ["../**/*"],
  "exclude": ["../node_modules"]
}
EOF

# Also create nuxt.d.ts
cat > .nuxt/nuxt.d.ts << 'EOF'
// Auto-generated by Nuxt
export {}
declare global {}
EOF

echo "🚀 Building Nuxt with FORCED TypeScript configs..."
NODE_OPTIONS="--max-old-space-size=4096" npx nuxt build

echo "✅ Build completed successfully!" 